[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
battlechain = "http://testnet.battlechain.com:3051"

[etherscan]
battlechain = { key = "not-required", url = "https://block-explorer-app-mu.vercel.app/" }
